'use strict';
function initialLanguage(){try{const saved=localStorage.getItem('cheers-language');if(locales.includes(saved))return saved;}catch{} const preferred=(navigator.languages?.[0]||navigator.language||'pt').split('-')[0].toLowerCase();return locales.includes(preferred)?preferred:'pt';}
let lang=initialLanguage(),category='all',query='',products=[],vibe=null,vibeIndex=0,menuFailed=false;
const labels={all:['Tudo','All'],cocktails:['Cocktails','Cocktails'],gins:['Gins','Gins'],vodkas:['Vodkas','Vodkas'],beers:['Cervejas','Beers'],packs:['Packs para partilhar','Sharing packs'],mocktails:['Sem álcool','Alcohol-free'],food:['Petiscos','Food'],sangrias:['Sangrias','Sangrias'],whiskeys:['Whiskeys','Whiskeys'],wine:['Vinhos','Wines'],shots:['Shots','Shots']};
const extraLabels={all:['Todo','Tout'],cocktails:['Cócteles','Cocktails'],gins:['Gins','Gins'],vodkas:['Vodkas','Vodkas'],beers:['Cervezas','Bières'],packs:['Packs para compartir','Packs à partager'],mocktails:['Sin alcohol','Sans alcool'],food:['Aperitivos','En-cas'],sangrias:['Sangrías','Sangrias'],whiskeys:['Whiskies','Whiskies'],wine:['Vinos','Vins'],shots:['Chupitos','Shots']};
Object.keys(labels).forEach(k=>labels[k].push(...extraLabels[k]));
const order=Object.keys(labels).slice(1), featuredIds=['cock-moj','cock-gin','cock-vod-mar'];
const $=s=>document.querySelector(s), tr=(pt,en)=>translate(pt,en);
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const money=p=>new Intl.NumberFormat(({pt:'pt-PT',en:'en-IE',es:'es-ES',fr:'fr-FR'})[lang],{style:'currency',currency:'EUR',minimumFractionDigits:Number.isInteger(p)?0:2}).format(p);
function productImage(p,featured=false){if(!p.image)return '';const illustrative=p.imageKind==='illustration';return `<div class="${featured?'featured-photo':'product-visual'}${illustrative?' illustration':''}"><img class="${featured?'':'product-photo'}" src="${escapeHTML(p.image)}" alt="${escapeHTML(p.name[lang])}${illustrative?tr(' — imagem ilustrativa',' — illustrative image'):''}" loading="lazy" decoding="async" width="${featured?400:88}" height="${featured?300:110}">${illustrative?`<span class="image-caption">${tr('Ilustrativa','Illustrative')}</span>`:''}</div>`;}

function renderFeatured(){if(!products.length)return; $('#featured').innerHTML=featuredIds.map((id,i)=>{const p=products.find(p=>p.id===id);return `<article class="feature">${productImage(p,true)}<span class="number">0${i+1}</span><span class="tag">${[tr('O CLÁSSICO DA CASA','THE HOUSE CLASSIC'),tr('PAIXÃO EM CAMPO','PASSION IN PLAY'),tr('MARACUJÁ AO PODER','PASSIONFRUIT POWER')][i]}</span><h3>${escapeHTML(p.name[lang])}</h3><p>${escapeHTML(p.description[lang])}</p><div class="feature-bottom"><span class="price">${money(p.price)}</span><button data-product="${id}">${tr('Ver no menu','View on menu')} ↗</button></div></article>`}).join(''); }
function renderCategories(){ $('#categories').innerHTML=Object.entries(labels).map(([key,value])=>`<button class="${category===key?'active':''}" aria-pressed="${category===key}" data-category="${key}">${value[locales.indexOf(lang)]}</button>`).join(''); }
function renderProducts(){const filtered=products.filter(p=>(category==='all'||p.category===category)&&norm(Object.values(p.name).join(' ')+' '+p.description[lang]+' '+(p.aliases||[]).join(' ')).includes(norm(query)));$('#count').textContent=`${filtered.length} ${tr('escolhas','choices')}`;$('#clear').hidden=!query;
 if(!filtered.length){$('#results').innerHTML=`<div class="empty"><h3>${tr('Não encontrámos esse sabor.','No matches this time.')}</h3><p>${tr('Experimenta outro nome ou volta ao menu completo.','Try another name or browse the full menu.')}</p><button class="primary" data-reset>${tr('Ver todo o menu','View full menu')}</button></div>`;return;}
 $('#results').innerHTML=order.map(cat=>{const items=filtered.filter(p=>p.category===cat);if(!items.length)return '';return `<section aria-labelledby="heading-${cat}"><div class="category-heading"><h3 id="heading-${cat}">${labels[cat][locales.indexOf(lang)]}</h3><span>${String(items.length).padStart(2,'0')} ${tr('ESCOLHAS','CHOICES')}</span></div><div class="product-grid">${items.map(p=>`<article class="product" id="${p.id}">${productImage(p)}<div class="product-copy">${featuredIds.includes(p.id)?`<span class="badge">★ ${tr('FAVORITO DA CASA','HOUSE FAVOURITE')}</span>`:''}<h4>${escapeHTML(p.name[lang])}</h4><p>${escapeHTML(p.description[lang])}</p></div><span class="price">${money(p.price)}</span></article>`).join('')}</div></section>`}).join('');}
function selectCategory(cat){category=cat;renderCategories();renderProducts();}
function updateLanguage(){document.documentElement.lang=lang;document.querySelectorAll('[data-pt]').forEach(el=>el.innerHTML=el.dataset[lang]||el.dataset.pt);$('#language').value=lang;$('#search').placeholder=tr('O que te apetece?');$('#search').setAttribute('aria-label',tr('Pesquisar produtos'));$('#clear').setAttribute('aria-label',tr('Limpar pesquisa'));$('#categories').setAttribute('aria-label',tr('Categorias do menu'));$('.bottom-nav').setAttribute('aria-label',tr('Navegação principal'));renderFeatured();renderBeerHighlight();renderCategories();if(menuFailed)renderError();else if(products.length)renderProducts();renderVibes();}
$('#language').addEventListener('change',e=>{if(!locales.includes(e.target.value))return;lang=e.target.value;try{localStorage.setItem('cheers-language',lang);}catch{}updateLanguage();});
$('#search').addEventListener('input',e=>{query=e.target.value;renderProducts();});
$('#clear').addEventListener('click',()=>{query='';$('#search').value='';renderProducts();$('#search').focus();});
$('#categories').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;selectCategory(b.dataset.category);$('#categories .active').scrollIntoView({block:'nearest',inline:'nearest'});});
$('#results').addEventListener('click',e=>{if(e.target.closest('[data-reset]')){query='';$('#search').value='';selectCategory('all');}});
$('#featured').addEventListener('click',e=>{const b=e.target.closest('[data-product]');if(!b)return;query='';$('#search').value='';selectCategory('cocktails');document.getElementById(b.dataset.product).scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});
$('#show-packs').addEventListener('click',()=>{query='';$('#search').value='';selectCategory('packs');$('#menu').scrollIntoView();});
document.querySelectorAll('.bottom-nav a').forEach(a=>a.addEventListener('click',()=>{document.querySelectorAll('.bottom-nav a').forEach(b=>b.classList.remove('selected'));a.classList.add('selected');if(a.getAttribute('href')==='#menu'){query='';$('#search').value='';selectCategory('all');}}));

const vibeChoices={fresh:{label:'Fresco & cítrico',drinks:['cock-moj','cock-mos'],food:'foo-tos'},tropical:{label:'Tropical',drinks:['cock-gin','cock-vod-mar'],food:'foo-piz'},bold:{label:'Intenso',drinks:['cock-esp','cock-neg'],food:'foo-tos'},zero:{label:'Zero álcool',drinks:['mock-rea','mock-vir'],food:'foo-piz'}};
function renderVibes(){
 $('#vibe-eyebrow').textContent=tr('CATEGORIA: TU DECIDES');$('#vibe-title').textContent=tr('Qual é a tua vibe?');$('#vibe-subtitle').textContent=tr('O árbitro aqui é o teu paladar.');$('#vibe-options').setAttribute('aria-label',tr('Qual é a tua vibe?'));
 $('#vibe-options').innerHTML=Object.entries(vibeChoices).map(([key,v])=>`<button data-vibe="${key}" aria-pressed="${vibe===key}" ${products.length?'':'disabled'}>${tr(v.label)}</button>`).join('');
 if(!vibe||!products.length){$('#vibe-result').innerHTML=`<p class="vibe-prompt">${tr('Escolhe uma vibe para descobrir a tua dupla.')}</p>`;return;}
 const choice=vibeChoices[vibe],drink=products.find(p=>p.id===choice.drinks[vibeIndex%choice.drinks.length]),food=products.find(p=>p.id===choice.food);
 $('#vibe-result').innerHTML=`<div class="duo"><div class="duo-drink">${productImage(drink)}<div><span class="eyebrow">${tr('A dupla da mesa.')}</span><h3>${escapeHTML(drink.name[lang])}</h3><p>${escapeHTML(drink.description[lang])}</p><strong>${money(drink.price)}</strong></div></div><div class="duo-food"><span>${tr('Combina com…')}</span><h3>${escapeHTML(food.name[lang])}</h3><p>${escapeHTML(food.description[lang])}</p><strong>${money(food.price)}</strong></div><div class="duo-actions"><span>${tr('Soma dos dois')} <strong>${money(drink.price+food.price)}</strong></span><p>${tr('Bebida + petisco. Preços individuais, sem compromisso.')}</p><div><button data-jump="${drink.id}">${tr('Ver bebida')} ↗</button><button data-jump="${food.id}">${tr('Ver petisco')} ↗</button><button data-another>${tr('Outra sugestão')} ⟳</button></div></div></div>`;
}
function jumpToProduct(id){const p=products.find(p=>p.id===id);if(!p)return;query='';$('#search').value='';selectCategory(p.category);const el=document.getElementById(id);el.setAttribute('tabindex','-1');el.focus({preventScroll:true});el.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
$('#vibe-options').addEventListener('click',e=>{const b=e.target.closest('[data-vibe]');if(!b)return;vibe=b.dataset.vibe;vibeIndex=0;renderVibes();});
$('#vibe-result').addEventListener('click',e=>{const b=e.target.closest('[data-jump]');if(b)jumpToProduct(b.dataset.jump);if(e.target.closest('[data-another]')){vibeIndex++;renderVibes();$('#vibe-result [data-another]').focus({preventScroll:true});}});
function renderError(){$('#results').innerHTML=`<div class="empty"><p>${tr('Não foi possível carregar o menu. Tenta novamente ou fala com a nossa equipa.')}</p><button class="primary" id="retry-menu">${tr('Tentar novamente')}</button></div>`;$('#retry-menu').addEventListener('click',()=>location.reload());}
updateLanguage();
fetch('menu.json').then(r=>{if(!r.ok)throw Error('menu');return r.json();}).then(data=>{products=data;updateLanguage();}).catch(()=>{menuFailed=true;renderError();});

function renderBeerHighlight(){
 const p=products.find(p=>p.id==='bee-gui');if(!p)return;
 $('#beer-highlight').innerHTML=`<div class="beer-highlight-photo"><img src="${escapeHTML(p.image)}" alt="Guinness — CHEERS O BAR" loading="lazy" decoding="async" width="941" height="1672"></div><div class="beer-highlight-copy"><span class="eyebrow">${tr('UM CLÁSSICO COM LUGAR CATIVO.')}</span><h2>${tr('O lado escuro<br>do bom gosto.')}</h2><p>${tr('Guinness na mesa. Conversa sem prolongamento.')}</p><div class="beer-highlight-price"><strong>Guinness</strong><span>${escapeHTML(p.description[lang])} · ${money(p.price)}</span></div><button class="primary" data-beer-product="${p.id}">${tr('Ver no menu')} ↗</button></div>`;
}
$('#beer-highlight').addEventListener('click',e=>{const b=e.target.closest('[data-beer-product]');if(b)jumpToProduct(b.dataset.beerProduct);});
