'use strict';
let lang='pt',category='all',query='',products=[];
const labels={all:['Tudo','All'],cocktails:['Cocktails','Cocktails'],gins:['Gins','Gins'],vodkas:['Vodkas','Vodkas'],beers:['Cervejas','Beers'],packs:['Packs para partilhar','Sharing packs'],mocktails:['Sem álcool','Alcohol-free'],food:['Petiscos','Food'],sangrias:['Sangrias','Sangrias'],whiskeys:['Whiskeys','Whiskeys'],wine:['Vinhos','Wines'],shots:['Shots','Shots']};
const order=Object.keys(labels).slice(1), featuredIds=['cock-moj','cock-gin','cock-vod-mar'];
const $=s=>document.querySelector(s), tr=(pt,en)=>lang==='pt'?pt:en;
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const money=p=>new Intl.NumberFormat(lang==='pt'?'pt-PT':'en-IE',{style:'currency',currency:'EUR',minimumFractionDigits:Number.isInteger(p)?0:2}).format(p);
function productImage(p,featured=false){if(!p.image)return '';const illustrative=p.imageKind==='illustration';return `<div class="${featured?'featured-photo':'product-visual'}${illustrative?' illustration':''}"><img class="${featured?'':'product-photo'}" src="${escapeHTML(p.image)}" alt="${escapeHTML(p.name[lang])}${illustrative?tr(' — imagem ilustrativa',' — illustrative image'):''}" loading="lazy" decoding="async" width="${featured?400:88}" height="${featured?300:110}">${illustrative?`<span class="image-caption">${tr('Ilustrativa','Illustrative')}</span>`:''}</div>`;}

function renderFeatured(){ $('#featured').innerHTML=featuredIds.map((id,i)=>{const p=products.find(p=>p.id===id);return `<article class="feature">${productImage(p,true)}<span class="number">0${i+1}</span><span class="tag">${[tr('O CLÁSSICO DA CASA','THE HOUSE CLASSIC'),tr('PAIXÃO EM CAMPO','PASSION IN PLAY'),tr('MARACUJÁ AO PODER','PASSIONFRUIT POWER')][i]}</span><h3>${escapeHTML(p.name[lang])}</h3><p>${escapeHTML(p.description[lang])}</p><div class="feature-bottom"><span class="price">${money(p.price)}</span><button data-product="${id}">${tr('Ver no menu','View on menu')} ↗</button></div></article>`}).join(''); }
function renderCategories(){ $('#categories').innerHTML=Object.entries(labels).map(([key,value])=>`<button class="${category===key?'active':''}" aria-pressed="${category===key}" data-category="${key}">${value[lang==='pt'?0:1]}</button>`).join(''); }
function renderProducts(){const filtered=products.filter(p=>(category==='all'||p.category===category)&&norm(p.name[lang]+' '+p.description[lang]).includes(norm(query)));$('#count').textContent=`${filtered.length} ${tr('escolhas','choices')}`;$('#clear').hidden=!query;
 if(!filtered.length){$('#results').innerHTML=`<div class="empty"><h3>${tr('Não encontrámos esse sabor.','No matches this time.')}</h3><p>${tr('Experimenta outro nome ou volta ao menu completo.','Try another name or browse the full menu.')}</p><button class="primary" data-reset>${tr('Ver todo o menu','View full menu')}</button></div>`;return;}
 $('#results').innerHTML=order.map(cat=>{const items=filtered.filter(p=>p.category===cat);if(!items.length)return '';return `<section aria-labelledby="heading-${cat}"><div class="category-heading"><h3 id="heading-${cat}">${labels[cat][lang==='pt'?0:1]}</h3><span>${String(items.length).padStart(2,'0')} ${tr('ESCOLHAS','CHOICES')}</span></div><div class="product-grid">${items.map(p=>`<article class="product" id="${p.id}">${productImage(p)}<div class="product-copy">${featuredIds.includes(p.id)?`<span class="badge">★ ${tr('FAVORITO DA CASA','HOUSE FAVOURITE')}</span>`:''}<h4>${escapeHTML(p.name[lang])}</h4><p>${escapeHTML(p.description[lang])}</p></div><span class="price">${money(p.price)}</span></article>`).join('')}</div></section>`}).join('');}
function selectCategory(cat){category=cat;renderCategories();renderProducts();}
function updateLanguage(){document.documentElement.lang=lang;document.querySelectorAll('[data-pt]').forEach(el=>el.innerHTML=el.dataset[lang]);$('#language').innerHTML=lang==='pt'?'PT <span>/ EN</span>':'<span>PT /</span> EN';$('#language').setAttribute('aria-label',tr('Change language to English','Mudar idioma para português'));$('#search').placeholder=tr('O que te apetece?','What are you in the mood for?');$('#search').setAttribute('aria-label',tr('Pesquisar produtos','Search products'));$('#clear').setAttribute('aria-label',tr('Limpar pesquisa','Clear search'));renderFeatured();renderCategories();renderProducts();}
$('#language').addEventListener('click',()=>{lang=lang==='pt'?'en':'pt';updateLanguage();});
$('#search').addEventListener('input',e=>{query=e.target.value;renderProducts();});
$('#clear').addEventListener('click',()=>{query='';$('#search').value='';renderProducts();$('#search').focus();});
$('#categories').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;selectCategory(b.dataset.category);$('#categories .active').scrollIntoView({block:'nearest',inline:'nearest'});});
$('#results').addEventListener('click',e=>{if(e.target.closest('[data-reset]')){query='';$('#search').value='';selectCategory('all');}});
$('#featured').addEventListener('click',e=>{const b=e.target.closest('[data-product]');if(!b)return;query='';$('#search').value='';selectCategory('cocktails');document.getElementById(b.dataset.product).scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});
$('#show-packs').addEventListener('click',()=>{query='';$('#search').value='';selectCategory('packs');$('#menu').scrollIntoView();});
document.querySelectorAll('.bottom-nav a').forEach(a=>a.addEventListener('click',()=>{document.querySelectorAll('.bottom-nav a').forEach(b=>b.classList.remove('selected'));a.classList.add('selected');}));
fetch('menu.json').then(r=>{if(!r.ok)throw Error('menu');return r.json();}).then(data=>{products=data;updateLanguage();}).catch(()=>{$('#results').innerHTML='<div class="empty"><p>Não foi possível carregar o menu. Tenta novamente ou fala com a nossa equipa.</p><button class="primary" onclick="location.reload()">Tentar novamente</button></div>';});
